name: CI

env:
  JDK_JAVA_OPTIONS: -XX:+PrintCommandLineFlags # JDK_JAVA_OPTIONS is _the_ env. variable to use for modern Java
  JVM_OPTS: -XX:+PrintCommandLineFlags # for Java 8 only (sadly, it is not modern enough for JDK_JAVA_OPTIONS)

'on':
  workflow_dispatch: {}
  release:
    types:
      - published
  push:
    branches:
      - main
  pull_request:
    branches-ignore:
      - gh-pages

jobs:
  lint:
    runs-on: ubuntu-22.04
    timeout-minutes: 30
    steps:
      - name: Checkout current branch
        uses: actions/checkout@v4.1.1
        with:
          fetch-depth: 0
      - name: Setup Scala and Java
        uses: olafurpg/setup-scala@v14
      - name: Cache Scala dependencies
        uses: coursier/cache-action@v6
      - name: Lint code
        run: sbt check

  mdoc:
    runs-on: ubuntu-22.04
    timeout-minutes: 60
    steps:
      - name: Checkout current branch
        uses: actions/checkout@v4.1.1
      - name: Setup Scala and Java
        uses: olafurpg/setup-scala@v14
      - name: Cache scala dependencies
        uses: coursier/cache-action@v6
      - name: Check Document Generation
        run: sbt compileDocs

  test:
    runs-on: ubuntu-22.04
    timeout-minutes: 30
    strategy:
      fail-fast: false
      matrix:
        java: ['adopt@1.8', 'adopt@1.11']
        scala: ['2.12.18', '2.13.12', '3.3.1']
        platform: ['JVM']
    steps:
      - name: Checkout current branch
        uses: actions/checkout@v4.1.1
        with:
          fetch-depth: 0
      - name: Setup Scala and Java
        uses: olafurpg/setup-scala@v14
        with:
          java-version: ${{ matrix.java }}
      - name: Cache Scala dependencies
        uses: coursier/cache-action@v6
      - name: Run tests
        run: sbt ++${{ matrix.scala }}! testJVM
      - name: Compile additional subprojects
        run: sbt ++${{ matrix.scala }}! examples/compile compileDocs

  ci:
    runs-on: ubuntu-22.04
    needs: [lint, mdoc, test]
    steps:
      - name: Report successful build
        run: echo "ci passed"

  publish:
    runs-on: ubuntu-22.04
    timeout-minutes: 30
    needs: [ci]
    if: github.event_name != 'pull_request'
    steps:
      - name: Checkout current branch
        uses: actions/checkout@v4.1.1
        with:
          fetch-depth: 0
      - name: Setup Scala and Java
        uses: olafurpg/setup-scala@v14
      - name: Cache Scala dependencies
        uses: coursier/cache-action@v6
      - name: Release artifacts
        run: sbt ci-release
        env:
          PGP_PASSPHRASE: ${{ secrets.PGP_PASSPHRASE }}
          PGP_SECRET: ${{ secrets.PGP_SECRET }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
          
  update-readme:
    name: Update README
    runs-on: ubuntu-latest
    continue-on-error: false
    if: ${{ github.event_name == 'push' }}
    steps:
      - name: Git Checkout
        uses: actions/checkout@v4.1.1
        with:
          fetch-depth: '0'
      - name: Install libuv
        run: sudo apt-get update && sudo apt-get install -y libuv1-dev
      - name: Setup Scala
        uses: actions/setup-java@v3.13.0
        with:
          distribution: corretto
          java-version: '17'
          check-latest: true
      - name: Cache Dependencies
        uses: coursier/cache-action@v6
      - name: Generate Readme
        run: sbt docs/generateReadme
      - name: Commit Changes
        run: |
          git config --local user.email "zio-assistant[bot]@users.noreply.github.com"
          git config --local user.name "ZIO Assistant"
          git add README.md
          git commit -m "Update README.md" || echo "No changes to commit"
      - name: Generate Token
        id: generate-token
        uses: zio/generate-github-app-token@v1.0.0
        with:
          app_id: ${{ secrets.APP_ID }}
          app_private_key: ${{ secrets.APP_PRIVATE_KEY }}
      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v5.0.2
        with:
          body: |-
            Autogenerated changes after running the `sbt docs/generateReadme` command of the [zio-sbt-website](https://zio.dev/zio-sbt) plugin.
            
            I will automatically update the README.md file whenever there is new change for README.md, e.g.
              - After each release, I will update the version in the installation section.
              - After any changes to the "docs/index.md" file, I will update the README.md file accordingly.
          branch: zio-sbt-website/update-readme
          commit-message: Update README.md
          token: ${{ steps.generate-token.outputs.token }}
          delete-branch: true
          title: Update README.md
      - name: Approve PR
        if: ${{ steps.cpr.outputs.pull-request-number }}
        run: gh pr review "$PR_URL" --approve
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_URL: ${{ steps.cpr.outputs.pull-request-url }}
      - name: Enable Auto-Merge
        if: ${{ steps.cpr.outputs.pull-request-number }}
        run: gh pr merge --auto --squash "$PR_URL" || gh pr merge --squash "$PR_URL"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_URL: ${{ steps.cpr.outputs.pull-request-url }}
          
  release-docs:
    name: Release Docs
    runs-on: ubuntu-latest
    continue-on-error: false
    needs:
      - publish
    if: ${{ ((github.event_name == 'release') && (github.event.action == 'published')) || (github.event_name == 'workflow_dispatch') }}
    steps:
      - name: Git Checkout
        uses: actions/checkout@v4.1.1
        with:
          fetch-depth: '0'
      - name: Install libuv
        run: sudo apt-get update && sudo apt-get install -y libuv1-dev
      - name: Setup Scala
        uses: actions/setup-java@v3.13.0
        with:
          distribution: corretto
          java-version: '17'
          check-latest: true
      - name: Cache Dependencies
        uses: coursier/cache-action@v6
      - name: Setup NodeJs
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          registry-url: https://registry.npmjs.org
      - name: Publish Docs to NPM Registry
        run: sbt docs/publishToNpm
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          
  notify-docs-release:
    name: Notify Docs Release
    runs-on: ubuntu-latest
    continue-on-error: false
    needs:
      - release-docs
    if: ${{ (github.event_name == 'release') && (github.event.action == 'published') }}
    steps:
      - name: Git Checkout
        uses: actions/checkout@v4.1.1
        with:
          fetch-depth: '0'
      - name: notify the main repo about the new release of docs package
        run: |
          PACKAGE_NAME=$(cat docs/package.json | grep '"name"' | awk -F'"' '{print $4}')
          PACKAGE_VERSION=$(npm view $PACKAGE_NAME version)
          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: token ${{ secrets.PAT_TOKEN }}"\
              https://api.github.com/repos/zio/zio/dispatches \
              -d '{
                    "event_type":"update-docs",
                    "client_payload":{
                      "package_name":"'"${PACKAGE_NAME}"'",
                      "package_version": "'"${PACKAGE_VERSION}"'"
                    }
                  }'
